# Generated by Django 4.2.7 on 2023-11-27 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Укажите свой номер телефона для пополнения баланса', max_length=20, validators=[main.utils.validate_phone_number], verbose_name='Номер телефона')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Сумма добавления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата пополнения')),
            ],
            options={
                'verbose_name': 'Пополнение баланса',
                'verbose_name_plural': 'Пополнения баланса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(max_length=20, validators=[main.utils.validate_phone_number], verbose_name='Номер отправителя')),
                ('recipient_phone', models.CharField(max_length=20, validators=[main.utils.validate_phone_number], verbose_name='Номер получателя')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Сумма перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Вставьте фото', null=True, upload_to='profile_image/', verbose_name='Фотография')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[main.utils.validate_phone_number], verbose_name='Номер телефона')),
                ('balance', models.PositiveIntegerField(default=100, verbose_name='Текущий баланс для этого профиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('user', models.OneToOneField(help_text='Связанный пользователь для этого профиля', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-created_at'],
            },
        ),
    ]
